const jobs=[
{title:'Analista de datos',company:'Banco Pichincha',location:'Quito',mode:'Híbrido',source:'LinkedIn público',skills:['sql','python','excel','power bi'],posted:'Hace 2 días',url:'https://www.linkedin.com/jobs/'},
{title:'Frontend Developer',company:'Kushki',location:'Quito',mode:'Remoto',source:'Multitrabajos',skills:['javascript','react','typescript','git'],posted:'Hace 1 día',url:'https://www.multitrabajos.com/'},
{title:'Especialista de marketing digital',company:'Pronaca',location:'Guayaquil',mode:'Presencial',source:'Socio Empleo',skills:['marketing','seo','google ads','analytics'],posted:'Hace 3 días',url:'https://encuentraempleo.trabajo.gob.ec/'},
{title:'Ingeniero/a de software',company:'PayPhone',location:'Cuenca',mode:'Híbrido',source:'LinkedIn público',skills:['java','spring','aws','docker'],posted:'Hace 4 días',url:'https://www.linkedin.com/jobs/'},
{title:'Coordinador de proyectos',company:'Grupo Nobis',location:'Guayaquil',mode:'Presencial',source:'Multitrabajos',skills:['project management','scrum','excel','liderazgo'],posted:'Hace 5 días',url:'https://www.multitrabajos.com/'},
{title:'Diseñador UX/UI',company:'Yagé',location:'Remoto',mode:'Remoto',source:'Multitrabajos',skills:['figma','ux','ui','research'],posted:'Hace 6 días',url:'https://www.multitrabajos.com/'},
{title:'Contador/a senior',company:'Corporación Favorita',location:'Quito',mode:'Presencial',source:'Socio Empleo',skills:['contabilidad','niif','excel','tributación'],posted:'Hace 1 semana',url:'https://encuentraempleo.trabajo.gob.ec/'},
{title:'Product Manager',company:'Banco Guayaquil',location:'Guayaquil',mode:'Híbrido',source:'LinkedIn público',skills:['product management','agile','analytics','liderazgo'],posted:'Hace 1 semana',url:'https://www.linkedin.com/jobs/'},
{title:'DevOps Engineer',company:'Tipti',location:'Quito',mode:'Remoto',source:'Multitrabajos',skills:['aws','kubernetes','docker','terraform'],posted:'Hace 1 semana',url:'https://www.multitrabajos.com/'},
{title:'Asistente administrativo',company:'Ministerio del Trabajo',location:'Quito',mode:'Presencial',source:'Socio Empleo',skills:['excel','organización','atención al cliente'],posted:'Hace 2 semanas',url:'https://encuentraempleo.trabajo.gob.ec/'}];
const catalog=[...jobs,...Array.from({length:14},(_,i)=>({...jobs[i%jobs.length],title:`${jobs[i%jobs.length].title} · oportunidad ${i+1}`,posted:'Hace 2 semanas'}))];let cvText='',activeSource='all';const $=s=>document.querySelector(s);const normalize=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
function score(job){if(!cvText)return null;const text=normalize(cvText);return Math.round(job.skills.filter(skill=>text.includes(normalize(skill))).length/job.skills.length*100)}
function render(){const term=normalize($('#searchInput').value),location=$('#locationFilter').value,mode=$('#modeFilter').value;const filtered=catalog.filter(job=>(activeSource==='all'||job.source===activeSource)&&(!term||normalize(`${job.title} ${job.company} ${job.skills.join(' ')}`).includes(term))&&(location==='all'||job.location===location)&&(mode==='all'||job.mode===mode)).sort((a,b)=>(score(b)||0)-(score(a)||0));$('#resultCount').textContent=`${filtered.length} resultado${filtered.length===1?'':'s'}`;$('#jobsList').innerHTML=filtered.length?filtered.map(job=>{const match=score(job);return `<article class="job-card ${cvText?'has-cv':''}"><div class="job-card-top"><div><h3>${job.title}</h3><p class="company">${job.company}</p></div><div class="job-source">${job.source}<br><span class="match-score">${match}% match</span></div></div><div class="job-meta"><span>⌖ ${job.location}</span><span>◷ ${job.mode}</span><span>${job.posted}</span><a class="apply-link" href="${job.url}" target="_blank" rel="noreferrer">Ver oferta ↗</a></div><div class="job-tags">${job.skills.map(skill=>`<span>${skill}</span>`).join('')}</div></article>`}).join(''):'<div class="empty">No encontramos vacantes con esos filtros. Prueba otra combinación.</div>'}
function openPicker(){ $('#cvInput').click() }['#topUpload','#heroUpload','#asideUpload','#cardUpload'].forEach(id=>$(id).addEventListener('click',openPicker));['#searchInput','#locationFilter','#modeFilter'].forEach(id=>$(id).addEventListener('input',render));$('#clearFilters').addEventListener('click',()=>{$('#searchInput').value='';$('#locationFilter').value='all';$('#modeFilter').value='all';activeSource='all';document.querySelectorAll('.source-chip').forEach((el,i)=>el.classList.toggle('active',i===0));render()});document.querySelectorAll('.source-chip').forEach(chip=>chip.addEventListener('click',()=>{activeSource=chip.dataset.source;document.querySelectorAll('.source-chip').forEach(el=>el.classList.toggle('active',el===chip));render()}));
async function readFile(file){if(file.type==='application/pdf'){const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;let text='';for(let page=1;page<=pdf.numPages;page++){const content=await(await pdf.getPage(page)).getTextContent();text+=content.items.map(item=>item.str).join(' ')+' '}return text}return file.text()}
$('#cvInput').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;if(file.size>5*1024*1024){alert('El archivo supera los 5 MB.');return}$('#uploadTitle').textContent='Analizando tu CV...';try{cvText=await readFile(file);const matches=catalog.map(score).filter(Boolean);const average=Math.round(matches.reduce((a,b)=>a+b,0)/(matches.length||1));const text=normalize(cvText),known=[...new Set(catalog.flatMap(job=>job.skills))],found=known.filter(skill=>text.includes(normalize(skill)));$('#uploadTitle').textContent=file.name;$('#uploadHint').textContent='CV analizado localmente';$('#cvResult').hidden=false;$('#cvResult').innerHTML=`<h3>Tu perfil está listo para comparar.</h3><p>Detectamos <strong>${found.length} habilidades</strong> y una afinidad promedio de <strong>${average}%</strong> en las vacantes disponibles.</p><div class="skills-found">${found.slice(0,12).map(skill=>`<span>${skill}</span>`).join('')}</div>`;$('#matchAside h3').textContent='Tu radar ya está personalizado.';$('#matchAside p').textContent='Las vacantes ahora están ordenadas por afinidad con tu perfil.';render();$('#vacantes').scrollIntoView({behavior:'smooth'})}catch(error){$('#uploadTitle').textContent='No pudimos leer ese archivo';$('#uploadHint').textContent='Prueba con PDF, TXT o MD';console.error(error)}});$('#heroCount').textContent=catalog.length;render();